const express = require("express")
const router =  express.Router()
const authRouter = require("./authRouter")
const userRouter = require("./userRouter")
const goodsRouter = require("./goodsRouter")
const orderRouter = require("./orderRouter")
const receivingRouter = require("./receivingRouter")
const billStatusRouter = require("./billStatusRouter")
const orderStatusRouter = require("./orderStatusRouter")
const paymentTypeRouter = require("./paymentTypeRouter")
const selectedProductRouter = require("./selectedProductRouter")
const authAndCheckRole = require("../middleware/checkAuthAndRoleMiddleware")

router.use('/auth', authRouter)
router.use('/users', userRouter)
router.use('/goods', goodsRouter)
router.use('/orders', orderRouter)
router.use('/receivings', authAndCheckRole(["USER", "EMPLOYEE","ADMIN"]), receivingRouter)
router.use('/bill-statuses', authAndCheckRole(["USER", "EMPLOYEE"]), billStatusRouter)
router.use('/payment-types', authAndCheckRole(["USER", "EMPLOYEE"]), paymentTypeRouter)
router.use('/order-statuses', authAndCheckRole(["USER", "EMPLOYEE"]), orderStatusRouter)
router.use('/selected-products', selectedProductRouter)

module.exports = router
